%YAML:1.0

File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 305.5
Camera1.fy: 307.2
Camera1.cx: 160.1
Camera1.cy: 119.26

Camera1.k1: 0.1021
Camera1.k2: -0.2492
Camera1.p1: 0.0025
Camera1.p2: 0.0051

Camera2.fx: 305.5
Camera2.fy: 307.2
Camera2.cx: 160.1
Camera2.cy: 119.26

Camera2.k1: 0.1021
Camera2.k2: -0.2492
Camera2.p1: 0.0025
Camera2.p2: 0.0051

Camera.width: 320
Camera.height: 240

#Camera.newWidth: 600
#Camera.newHeight: 350

# Camera frames per second 
Camera.fps: 22

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 60.0
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [1.0,0,0,0,
         0,0.769399555046892,0.63876781751560,0.0459,
         0,-0.63876781751560,0.769399555046892,-0.008,
         0,0,0,1.000000000000000]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0